apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    project: demo-voting-app
spec:
  selector:
    app: voting-app-postgres
    project: demo-voting-app
  ports:
  - port: 5432
    targetPort: 5432
