apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    project: demo-voting-app
spec:
  selector:
    app: voting-app-redis
    project: demo-voting-app
  ports:
  - port: 6379
    targetPort: 6379
