apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    project: demo-result-app
spec:
  type: NodePort
  selector:
    app: result-app
    project: demo-voting-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30005
