apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    project: demo-voting-app
spec:
  type: NodePort
  selector:
    app: voting-app
    project: demo-voting-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30006

