apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-worker
spec:
  selector:
    matchLabels:
      app: voting-app-worker
  template:
    metadata:
      labels:
        app: voting-app-worker
        project: demo-voting-app
    spec:
      containers:
      - name: worker
        image: kodekloud/examplevotingapp_worker:v1
